Add script to try to build all archlinux-community pkg

diff --git a/2.9/packages/build-packages b/2.9/packages/build-packages
--- a/2.9/packages/build-packages
+++ b/2.9/packages/build-packages
@@ -232,6 +232,7 @@ fi
     [ ! -e $SOURCE_DIR ] && svn co $ARCHIVE
     cd $SOURCE_DIR
     [ -e libc ] && cd libc # eglibc
+    echo "db-autobuild for svn"
     db-autobuild $DIBAB_PREFIX/$MODULE 2>ydfs-error 1>ydfs-log || exit $?
     continue
   fi
@@ -241,6 +242,7 @@ fi
     SOURCE_DIR=`echo $ARCHIVE | cut -d':' -f2`
     [ ! -e $SOURCE_DIR ] && bzr checkout --lightweight $ARCHIVE
     cd $SOURCE_DIR
+    echo "db-autobuild for lp"
     db-autobuild $DIBAB_PREFIX/$MODULE 2>ydfs-error 1>ydfs-log || touch $HOME/ydfs-error
     [ -e $HOME/ydfs-error ] && echo "Exit $ARCHIVE " && break
     [ -e $HOME/ydfs-error ] && tail ydfs-error && echo "Exit $ARCHIVE " && break
@@ -280,12 +282,13 @@ fi
 	    echo "Cloning $ARCHIVE (quiet)"
         [ ! -e $SOURCE_DIR ] && git clone -q `echo $ARCHIVE |cut -d'#' -f1`
     fi
+    # [ ! -e $SOURCE_DIR ] &&  [ "$NOTEXIT" = "OK" ] && echo "Clone faild with $0, but we continue " && continue
     cd $SOURCE_DIR
     TAG=`echo $ARCHIVE | grep '#tag' | cut -d'=' -f2`
     COMMIT=`echo $ARCHIVE | grep '#commit' | cut -d'=' -f2`
     if [ "$TAG" != "" ]
     then
-	git checkout -q tags/$TAG || exit 1
+	git checkout -q tags/$TAG ||  git checkout -q $TAG # || exit 1
     fi
     [ "$COMMIT" != "" ] && echo "At commit $COMMIT" &&  git checkout  $COMMIT && sleep 5
     # [ ! -n "$REVISION" ] && git reset --hard $REVISION 
@@ -294,6 +297,7 @@ fi
 
     [ -e ./data/gala.desktop ] && git cherry-pick -n 85d290c75eaa147b704ad34e6c67498071707ee8
     build_ydfs_package
+    [ -e $HOME/ydfs-error ] && [ "$NOTEXIT" = "OK" ] && echo "Build faild with $0, but we continue " && continue
     [ -e $HOME/ydfs-error ] && tail ydfs-error && echo "Exit $ARCHIVE " && break
     continue
   fi
@@ -317,6 +321,7 @@ fi
     continue
   fi
 
+  [ -e $HOME/ydfs-error ] && [ "$NOTEXIT" = "OK" ] && echo "Build faild with $0, but we continue " && continue
   [ -e $HOME/ydfs-error ] && echo "Final exit $0 " && break
 
   if [ -e $HOME/ydfs/tarballs/`basename $ARCHIVE` ]
@@ -333,7 +338,7 @@ fi
    file $HOME/ydfs/tarballs/`basename $ARCHIVE` | grep HTML && rm $HOME/ydfs/tarballs/`basename $ARCHIVE`
   [ ! -e $HOME/ydfs/tarballs/`basename $ARCHIVE` ] && echo " not found " 
 
-  # Second pass, go into LinuxConsole reposotory
+  # Second pass, go into LinuxConsole repository
   [ ! -e $HOME/ydfs/tarballs/`basename $ARCHIVE` ] && touch $HOME/ydfs/tarballs/`basename $ARCHIVE`.start && echo && echo -n "Now trying http://jukebox.linuxconsole.org/sources/$(basename $ARCHIVE) ..." && LD_LIBRARY_PATH="" wget -q --trust-server-name --tries=5 -w 6 --no-check-certificate --output-document=$HOME/ydfs/tarballs/`basename $ARCHIVE` http://jukebox.linuxconsole.org/sources/$(basename $ARCHIVE) && rm $HOME/ydfs/tarballs/`basename $ARCHIVE`.start
     test -s $HOME/ydfs/tarballs/`basename $ARCHIVE` || rm $HOME/ydfs/tarballs/`basename $ARCHIVE`
   [ ! -e $HOME/ydfs/tarballs/`basename $ARCHIVE` ] && echo " not found !!!" && echo && touch $HOME/ydfs-error && exit 1
@@ -391,7 +396,7 @@ fi
 	# echo -n  " .. Running db-lcarchive $HOME/ydfs/tarballs/$(basename $ARCHIVE)"
 	DBKVER=$KERNEL3 LC_CONFIGURE_OPTS="$LC_CONFIGURE_OPTS" LCARCHIVE_CHOICE=installfromsrc db-lcarchive $HOME/ydfs/tarballs/`basename $ARCHIVE` || touch $HOME/ydfs-error
        
-	if [ -e $HOME/ydfs-error ]
+	if [ -e $HOME/ydfs-error ] &&  [ "$NOTEXIT" != "OK" ]
         then
 	   echo "Exit db-lcarchive $ARCHIVE, because $HOME/ydfs-error exists " 
    	   exit 1	
diff --git a/2.9/packages/db-autobuild b/2.9/packages/db-autobuild
--- a/2.9/packages/db-autobuild
+++ b/2.9/packages/db-autobuild
@@ -411,6 +411,7 @@ Cflags: ' > $PREFIX/lib/pkgconfig/id3tag.pc
   [ -e $HOME/$ARCH/include/gtest-disabled ] && mv $HOME/$ARCH/include/gtest-disabled $HOME/$ARCH/include/gtest
   [ -e $HOME/$ARCH/include/gmock-disabled ] && mv $HOME/$ARCH/include/gmock-disabled $HOME/$ARCH/include/gmock
   [ -e $HOME/$ARCH/include/libavutil-disabled ] && mv $HOME/$ARCH/include/libavutil-disabled $HOME/$ARCH/include/libavutil
+  [ -e $HOME/$ARCH/include/png-disabled.h ] && mv $HOME/$ARCH/include/png-disabled.h $HOME/$ARCH/include/png.h
   [ -e $HOME/$ARCH/include/libavformat-disabled ] && mv $HOME/$ARCH/include/libavformat-disabled $HOME/$ARCH/include/libavformat
   [ -e $HOME/$ARCH/include/libswscale-disabled ] && mv $HOME/$ARCH/include/libswscale-disabled $HOME/$ARCH/include/libswscale
   [ -e $HOME/$ARCH/include/unicode-disabled ] && mv $HOME/$ARCH/include/unicode-disabled $HOME/$ARCH/include/unicode
@@ -611,7 +612,7 @@ grep share/Surge src/common/SurgeStorage.cpp
       cd ..
       install -d $PREFIX/lib/vst3
       install -d $PREFIX/share/Surge
-      cp -av resources/data/* $PREFIX/share/Surge || exit 2
+      cp -av resources/data/* $PREFIX/share/Surge || exit 222
       echo "Install VST3"
       cp -fR build/surge_xt_products/*.vst3 $PREFIX/lib/vst3 || exit 1
       echo "Install Standalone"
@@ -641,7 +642,7 @@ grep share/Surge src/common/SurgeStorage.cpp
       install -d $PREFIX/lib/vst3
       install -d $PREFIX/lib/lv2
       install -d $PREFIX/share/Surge
-      cp -av resources/data/* $PREFIX/share/Surge || exit 2
+      cp -av resources/data/* $PREFIX/share/Surge || exit 3
       cp -fR build/surge_products/Surge.lv2 $PREFIX/lib/lv2 || exit 1
       cp -fR build/surge_products/Surge.vst3 $PREFIX/lib/vst3 || exit 1
     touch buildok-$ARCH
@@ -1153,7 +1154,7 @@ pwd && sleep 5
   	cp $HOME/$ARCH/include/GL/wglext.h source/Irrlicht/wglext.h
 	cd source/Irrlicht
 	rm */*.o
-	CFLAGS="" CPPFLAGS="" CXXFLAGS="-I$HOME/$ARCH/include -std=gnu++11 -fPIC" make NDEBUG=1 sharedlib	 || exit 2
+	CFLAGS="" CPPFLAGS="" CXXFLAGS="-I$HOME/$ARCH/include -std=gnu++11 -fPIC" make NDEBUG=1 sharedlib	 || exit 4
 	make install || exit 3
   	cd ../../
 	touch buildok-$ARCH
@@ -1194,7 +1195,7 @@ pwd && sleep 5
   then
     mkdir build
     cd build
-    cmake ../ -GNinja -DCMAKE_INSTALL_PREFIX=$PREFIX || exit 2
+    cmake ../ -GNinja -DCMAKE_INSTALL_PREFIX=$PREFIX || exit 5
     ninja || exit 1
     ninja xmoto_pack
     ninja install
@@ -1747,7 +1748,12 @@ CMAKEOPTIONS="-DOPUSFILE_LIBRARY=$HOME/$ARCH/lib/libopus.so.0 -DOPUS_INCLUDE_DIR
 	 	exit 0
 	fi	
         [ -e ../src/wesnoth.cpp ] && echo "Unsetting $ARCH" && sleep 5 && OLDARCH=$ARCH && unset ARCH && export CXX=clang++
-	cmake $CMAKEOPTIONS .. || exit 12
+        if  [ "$NOTEXIT" = "OK" ] 
+	then
+	      cmake $CMAKEOPTIONS .. || exit 0
+	else
+		cmake $CMAKEOPTIONS .. || exit 12
+	fi
         [ -e ../src/wesnoth.cpp ] && export ARCH=$OLDARCH
 
         if [ -e ../Source/WebKit/gtk/ ]
@@ -2656,7 +2662,8 @@ Cflags: -I${includedir}' > lua.pc
       #make DBM_INCLUDE=$HOME/$OLDARCH/include -n -k -j3 
       make DBM_INCLUDE=$HOME/$OLDARCH/include WARNINGS_AS_ERRORS=n $MAKEOPT || make
       if [ $? != 0 ]
-      then
+      then 
+	echo "Make failed .."
 	if [ -e  $SOURCEDIR/configure ] && [ ! -e $SOURCEDIR/configure.log ]
 	then
 	  exit 21
@@ -2775,6 +2782,7 @@ Cflags: -I${includedir}' > lua.pc
 	if [ $return != "0" ]
 	then
 	  echo "Return is $return"
+	  [ "$NOTEXIT" = "OK" ] && echo "Build faild, but we continue" && exit 0
 	  exit 23
 	fi
 	[ -e flatc  ] && install -d $PREFIX/bin/ && cp flatc $PREFIX/bin
diff --git a/2.9/scripts/includes/build b/2.9/scripts/includes/build
--- a/2.9/scripts/includes/build
+++ b/2.9/scripts/includes/build
@@ -6,7 +6,13 @@ build_ydfs_package()
   if [ "$BUILDME" = "OK" ] || [ "$DIBAB_VERBOSE_BUILD" = "YES" ] || echo $PWD | grep x11-xserver-utils
   then
   export LC_CONFIGURE_OPTS
-  db-autobuild $MYPREFIX || exit $?
+  echo "db-autobuild from build_ydfs_package - verbose"
+  db-autobuild $MYPREFIX 
+  EXITCODE=$?
+  if [ "$EXITCODE" != "0" ]
+  then
+     [ "$NOTEXIT" != "OK" ] && echo "Exit 1" && exit 1
+  fi 
   else
   PKGNAME=`basename $PWD`
   echo -n "Building $PKGNAME in progress, "     
@@ -19,11 +25,15 @@ build_ydfs_package()
   START=`date '+%s'`
   [ -e ydfs-log ] && [ ! -e ydfs-log.1rst ] && cp ydfs-log ydfs-log.1rst
 #echo "Run build_ydfs_package from scripts/includes/build"
+  echo "db-autobuild from build_ydfs_package - logfile"
   db-autobuild $MYPREFIX 2>ydfs-error 1>ydfs-log
   EXITCODE=$?
 #echo "Exit code is $EXITCODE"
-  [ "$EXITCODE" != "0" ] && LOGERROR=`tail ydfs-error` && echo -n -e "\n \e[31mFAILED $PWD\e[0m \n" && echo -n -e "\n\n \e[31m$LOGERROR\e[0m \n" && echo -e "\n Error log at $PWD/ydfs-error \n\n" 
-  [ "$EXITCODE" != "0" ] && exit 1
+  if [ "$EXITCODE" != "0" ]
+  then
+     LOGERROR=`tail ydfs-error` && echo -n -e "\n \e[31mFAILED $PWD\e[0m \n" && echo -n -e "\n\n \e[31m$LOGERROR\e[0m \n" && echo -e "\n Error log at $PWD/ydfs-error \n\n" 
+     [ "$NOTEXIT" != "OK" ] && echo "Exit 1" && exit 1
+  fi
   END=`date '+%s'`
   DURATION=$((($END - $START)/60))
   SDURATION=$((($END - $START)%60))
