dibab to ydfs

diff --git a/2.5/packages/build-packages b/2.5/packages/build-packages
--- a/2.5/packages/build-packages
+++ b/2.5/packages/build-packages
@@ -34,7 +34,7 @@ unset CLEARENV XDG_DATA_DIRS PKG_CONFIG_PATH CFLAGS CXXFLAGS CPPFLAGS LDFLAGS LD
 
 # $1 est supposée être une ISO particulière demandée passée en paramètre, lanpower, par exemple: pourquoi est-ce "uclib" ici ? 
 # Sinon, La ligne 14 "echo $SRC_PATH/list-$1" donne n'importe quoi
-[ "$1" = "uclib" ] && export CC=$HOME/dibab/x-tools/i386-unknown-linux-uclibc/bin/i386-unknown-linux-uclibc-gcc
+[ "$1" = "uclib" ] && export CC=$HOME/ydfs/x-tools/i386-unknown-linux-uclibc/bin/i386-unknown-linux-uclibc-gcc
 # initialisation du chemin pour le compilateur C x86
 [ "$ARCH" = "x86" ] && [ "$CC" = "" ] && export CC=`which gcc`
 
@@ -57,13 +57,13 @@ echo "ACLOCAL_FLAGS is $ACLOCAL_FLAGS"
 # création d'un répertoire
 [ ! -e $HOME/$MODULE/share/aclocal ] && install -d $HOME/$MODULE/share/aclocal
 # initialisations des variables utilisées 
-install -d $HOME/dibab/CFLAGS
-install -d $HOME/dibab/CPPFLAGS
-install -d $HOME/dibab/CPPFLAGS
+install -d $HOME/ydfs/CFLAGS
+install -d $HOME/ydfs/CPPFLAGS
+install -d $HOME/ydfs/CPPFLAGS
 export CMAKE_LIBRARY_PATH=$CMAKE_LIBRARY_PATH:/$HOME/$MODULE/lib:$HOME/$ARCH/lib CMAKE_INCLUDE_PATH=$CMAKE_INCLUDE_PATH:$HOME/$MODULE/include:$HOME/$ARCH/include
-export CFLAGS="$CFLAGS -O2 -I. -I""$HOME/$MODULE/include -I$HOME/dibab/CFLAGS"
-export CPPFLAGS="$CPPFLAGS -I""$HOME/$MODULE/include -I$HOME/dibab/CPPFLAGS"
-export CXXFLAGS="$CXXFLAGS -I""$HOME/$MODULE/include -I$HOME/dibab/CXXFLAGS"
+export CFLAGS="$CFLAGS -O2 -I. -I""$HOME/$MODULE/include -I$HOME/ydfs/CFLAGS"
+export CPPFLAGS="$CPPFLAGS -I""$HOME/$MODULE/include -I$HOME/ydfs/CPPFLAGS"
+export CXXFLAGS="$CXXFLAGS -I""$HOME/$MODULE/include -I$HOME/ydfs/CXXFLAGS"
 export CXXFLAGS="$CXXFLAGS -I""$HOME/$ARCH/include"
 export CXXFLAGS="$CXXFLAGS -I""$HOME/$ARCH/include/AL"
 export CXXFLAGS="$CXXFLAGS -I""$HOME/$ARCH/include/irrlicht"
@@ -72,7 +72,7 @@ export LDFLAGS="$LDFLAGS -L""$HOME/$MODULE/lib "
 export LDFLAGS="$LDFLAGS -L""$HOME/$MODULE/lib64 "
 export GTKMM_BASEPATH=$HOME/$ARCH
 # autres initialisations selon les architectures(processeurs)
-[ "$ARCH" = "arm" ] && export LDFLAGS="$LDFLAGS -Wl,-rpath-link,$HOME/$ARCH/lib -Wl,-rpath-link,/home/raspi/dibab/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/lib" # FIXME
+[ "$ARCH" = "arm" ] && export LDFLAGS="$LDFLAGS -Wl,-rpath-link,$HOME/$ARCH/lib -Wl,-rpath-link,/home/raspi/ydfs/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/lib" # FIXME
 [ "$ARCH" = "x86" ] && export LDFLAGS="$LDFLAGS -Wl,-rpath-link,$HOME/$MODULE/lib"
 [ "$ARCH" = "x86_64" ] && export LDFLAGS="$LDFLAGS -Wl,-rpath-link,$HOME/$MODULE/lib64 -Wl,-rpath-link,$HOME/$MODULE/lib"
 export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/$MODULE/lib"
@@ -89,7 +89,7 @@ PATH=$PWD:$PATH
 else
 PATH=$PWD:$HOME/Qt5/5.4/gcc/bin:$MODULEPATH:$PATH:
 fi
-PATH=$HOME/dibab/llvm-clang/bin/:$PATH
+PATH=$HOME/ydfs/llvm-clang/bin/:$PATH
 test -n "$1" && MODULE="$1"
 # build tar
 whoami | grep root && export FORCE_UNSAFE_CONFIGURE=1
@@ -107,7 +107,7 @@ export CUPS_ETC=$DIBAB_PREFIX/$ARCH/etc
 LIST2=$SRC_PATH/list-$LIST
 [ -n "$1" ] && [ -e $SRC_PATH/list-$1 ] && LIST2=$SRC_PATH/list-$1
 
-[ -e $HOME/dibab-error ] && rm $HOME/dibab-error
+[ -e $HOME/ydfs-error ] && rm $HOME/ydfs-error
 
 #$HOME_DIBAB/scripts/first-env
 
@@ -159,8 +159,8 @@ then
   echo "Arch linux source for $PKG : $ARCHIVE_URL"
 fi
   DIRNAME=`basename $ARCHIVE_URL |sed "s/.tar.xz//" | sed "s/.tar.bz2//" | sed "s/.tar.gz//"`
-  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME/dibab/build-$ARCH/$DIRNAME/"buildok-"$ARCH ] && echo "$HOME/dibab/build-$ARCH/$DIRNAME/"buildok-"$ARCH exists" && continue
-  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME/dibab/packages-$ARCH/$DIRNAME ] && echo "$HOME/dibab/packages-$ARCH/$DIRNAME exists" && continue
+  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME/ydfs/build-$ARCH/$DIRNAME/"buildok-"$ARCH ] && echo "$HOME/ydfs/build-$ARCH/$DIRNAME/"buildok-"$ARCH exists" && continue
+  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME/ydfs/packages-$ARCH/$DIRNAME ] && echo "$HOME/ydfs/packages-$ARCH/$DIRNAME exists" && continue
   FIRST=`echo $ARCHIVE | head -c1`
   [ "$FIRST" = '#' ] && continue
   ARCHIVE=`echo $ARCHIVE|cut -d'#' -f1`
@@ -171,10 +171,10 @@ fi
   export MYPREFIX=$DIBAB_PREFIX/$MODULE/
   echo $ARCHIVE | grep grub && unset CFLAGS && unset LDFLAGS #export FIRSTENV="OK"
   echo $ARCHIVE | grep warzone && export CLEARENV="OK"
-  echo $ARCHIVE | grep lxpanel && install -d $HOME/dibab/build-$ARCH/lxpanel/data/ui # FIXME
+  echo $ARCHIVE | grep lxpanel && install -d $HOME/ydfs/build-$ARCH/lxpanel/data/ui # FIXME
   if [  -n "`echo $ARCHIVE | grep 'svn://'`" ] 
   then
-    cd $HOME/dibab/src
+    cd $HOME/ydfs/src
     SOURCE_DIR=`basename $ARCHIVE | cut -d'.' -f1`
     [ ! -e $SOURCE_DIR ] && svn co $ARCHIVE
     cd $SOURCE_DIR
@@ -184,54 +184,54 @@ fi
   fi
   if [  -n "`echo $ARCHIVE | grep 'lp:'`" ] 
   then
-    cd $HOME/dibab/src
+    cd $HOME/ydfs/src
     SOURCE_DIR=`echo $ARCHIVE | cut -d':' -f2`
     [ ! -e $SOURCE_DIR ] && bzr checkout --lightweight $ARCHIVE
     cd $SOURCE_DIR
-    db-autobuild $DIBAB_PREFIX/$MODULE || touch $HOME/dibab-error
-    [ -e $HOME/dibab-error ] && echo "Exit $ARCHIVE " && break
+    db-autobuild $DIBAB_PREFIX/$MODULE || touch $HOME/ydfs-error
+    [ -e $HOME/ydfs-error ] && echo "Exit $ARCHIVE " && break
     continue
   fi
   if [  -n "`echo $ARCHIVE | grep 'git://'`" ] || [  -n "`echo $ARCHIVE | grep 'opkg-gtk2.git'`" ] 
   then
-    cd $HOME/dibab/src
+    cd $HOME/ydfs/src
     echo $ARCHIVE | grep '#' && REVISION=$(echo $ARCHIVE | cut -d'#' -f2| cut -d= -f2) && ARCHIVE=$(echo $ARCHIVE | cut -d'#' -f1)
     SOURCE_DIR=`basename $ARCHIVE | cut -d'.' -f1`
     #[ "$SOURCE_DIR" = "core" ] && SOURCE_DIR=libreoffice
     [ ! -e $SOURCE_DIR ] && git clone $ARCHIVE
     cd $SOURCE_DIR
     [ ! -n "$REVISION" ] && git reset --hard $REVISION 
-    db-autobuild $DIBAB_PREFIX/$MODULE || touch $HOME/dibab-error
-    [ -e $HOME/dibab-error ] && echo "Exit $ARCHIVE " && break
+    db-autobuild $DIBAB_PREFIX/$MODULE || touch $HOME/ydfs-error
+    [ -e $HOME/ydfs-error ] && echo "Exit $ARCHIVE " && break
     continue
   fi
   if [  -n "`echo $ARCHIVE | grep 'CPAN:/'`" ] 
   then
     modperl=`echo $ARCHIVE | cut -d '/' -f2` 
     echo "Run  db-build-modperl $modperl" 
-	  SDL_INC=$HOME/$ARCH/include SDL_LIB=$HOME/$ARCH/lib db-build-modperl $modperl || touch $HOME/dibab-error
-    [ -e $HOME/dibab-error ] && echo "Exit $ARCHIVE " && break
+	  SDL_INC=$HOME/$ARCH/include SDL_LIB=$HOME/$ARCH/lib db-build-modperl $modperl || touch $HOME/ydfs-error
+    [ -e $HOME/ydfs-error ] && echo "Exit $ARCHIVE " && break
     continue
   fi
 
-  [ -e $HOME/dibab-error ] && echo "Exit $0 " && break
+  [ -e $HOME/ydfs-error ] && echo "Exit $0 " && break
 
-  if [ -e $HOME/dibab/tarballs/`basename $ARCHIVE` ]
+  if [ -e $HOME/ydfs/tarballs/`basename $ARCHIVE` ]
   then
-    test -s $HOME/dibab/tarballs/`basename $ARCHIVE` || rm $HOME/dibab/tarballs/`basename $ARCHIVE`
+    test -s $HOME/ydfs/tarballs/`basename $ARCHIVE` || rm $HOME/ydfs/tarballs/`basename $ARCHIVE`
   fi
-  [ -e $HOME/dibab/tarballs/`basename $ARCHIVE`.start ] && [ -e $HOME/dibab/tarballs/`basename $ARCHIVE` ] && rm $HOME/dibab/tarballs/`basename $ARCHIVE`
+  [ -e $HOME/ydfs/tarballs/`basename $ARCHIVE`.start ] && [ -e $HOME/ydfs/tarballs/`basename $ARCHIVE` ] && rm $HOME/ydfs/tarballs/`basename $ARCHIVE`
 
   # First pass, go into source LinuxConsole
   echo
-  [ ! -e $HOME/dibab/tarballs/`basename $ARCHIVE` ] && touch $HOME/dibab/tarballs/`basename $ARCHIVE`.start && echo -n "Get $ARCHIVE ..." && wget -q --trust-server-name --tries=5 -w 6 --no-check-certificate --output-document=$HOME/dibab/tarballs/`basename $ARCHIVE` $ARCHIVE && rm $HOME/dibab/tarballs/`basename $ARCHIVE`.start
-    test -s $HOME/dibab/tarballs/`basename $ARCHIVE` || rm $HOME/dibab/tarballs/`basename $ARCHIVE`
-  [ ! -e $HOME/dibab/tarballs/`basename $ARCHIVE` ] && echo " not found " && touch $HOME/dibab-error
+  [ ! -e $HOME/ydfs/tarballs/`basename $ARCHIVE` ] && touch $HOME/ydfs/tarballs/`basename $ARCHIVE`.start && echo -n "Get $ARCHIVE ..." && wget -q --trust-server-name --tries=5 -w 6 --no-check-certificate --output-document=$HOME/ydfs/tarballs/`basename $ARCHIVE` $ARCHIVE && rm $HOME/ydfs/tarballs/`basename $ARCHIVE`.start
+    test -s $HOME/ydfs/tarballs/`basename $ARCHIVE` || rm $HOME/ydfs/tarballs/`basename $ARCHIVE`
+  [ ! -e $HOME/ydfs/tarballs/`basename $ARCHIVE` ] && echo " not found " && touch $HOME/ydfs-error
 
   # Second pass, go into LinuxConsole reposotory
-  [ ! -e $HOME/dibab/tarballs/`basename $ARCHIVE` ] && touch $HOME/dibab/tarballs/`basename $ARCHIVE`.start && echo && echo -n "Now trying http://jukebox.linuxconsole.org/sources/$(basename $ARCHIVE) ..." && wget -q --trust-server-name --tries=5 -w 6 --no-check-certificate --output-document=$HOME/dibab/tarballs/`basename $ARCHIVE` http://jukebox.linuxconsole.org/sources/$(basename $ARCHIVE) && rm $HOME/dibab/tarballs/`basename $ARCHIVE`.start
-    test -s $HOME/dibab/tarballs/`basename $ARCHIVE` || rm $HOME/dibab/tarballs/`basename $ARCHIVE`
-  [ ! -e $HOME/dibab/tarballs/`basename $ARCHIVE` ] && echo " not found !!!" && echo && touch $HOME/dibab-error && exit 1
+  [ ! -e $HOME/ydfs/tarballs/`basename $ARCHIVE` ] && touch $HOME/ydfs/tarballs/`basename $ARCHIVE`.start && echo && echo -n "Now trying http://jukebox.linuxconsole.org/sources/$(basename $ARCHIVE) ..." && wget -q --trust-server-name --tries=5 -w 6 --no-check-certificate --output-document=$HOME/ydfs/tarballs/`basename $ARCHIVE` http://jukebox.linuxconsole.org/sources/$(basename $ARCHIVE) && rm $HOME/ydfs/tarballs/`basename $ARCHIVE`.start
+    test -s $HOME/ydfs/tarballs/`basename $ARCHIVE` || rm $HOME/ydfs/tarballs/`basename $ARCHIVE`
+  [ ! -e $HOME/ydfs/tarballs/`basename $ARCHIVE` ] && echo " not found !!!" && echo && touch $HOME/ydfs-error && exit 1
 
   echo $ARCHIVE | grep xslt && [ -e $DIBAB_PREFIX/$MODULE/include/libxml2/libxml ] && [ ! -e $DIBAB_PREFIX/$MODULE/include/libxml ] && ln -s $DIBAB_PREFIX/$MODULE/include/libxml2/libxml $DIBAB_PREFIX/$MODULE/include
 
@@ -249,10 +249,10 @@ fi
   echo $ARCHIVE | grep json-c && export CFLAGS="$CFLAGS -Wno-error"
   echo $ARCHIVE | grep jasper && export LDFLAGS="$LDFLAGS -fPIC" && export CFLAGS="$CFLAGS -fPIC"
   echo $ARCHIVE | grep foomatic-db-engine && export LIBDIR=$DIBAB_PREFIX/$MODULE/share/foomatic 
-  echo $ARCHIVE | grep gtk+-2.24 && export CFLAGS="$CFLAGS -Wl,-rpath-link,$HOME/dibab/build-x86/gtk+-2.24.9/gdk/.libs/"
-  echo $ARCHIVE | grep kino && export CFLAGS=" -I/$HOME/dibab/src/kino-1.3.4/ffmpeg " && echo "CFLAGS is $CFLAGS"
-  echo $ARCHIVE | grep udev-164 && export CFLAGS="$CFLAGS -Wl,-rpath-link,$HOME/dibab/build-x86/udev-164/libudev/.libs/"
-  echo $ARCHIVE | grep gst-plugins-base-0.10.35 && export CFLAGS="$CFLAGS -Wl,-rpath-link,$HOME/dibab/build-x86/gst-plugins-base-0.10.35/gst-libs/gst/interfaces/.libs/"
+  echo $ARCHIVE | grep gtk+-2.24 && export CFLAGS="$CFLAGS -Wl,-rpath-link,$HOME/ydfs/build-x86/gtk+-2.24.9/gdk/.libs/"
+  echo $ARCHIVE | grep kino && export CFLAGS=" -I/$HOME/ydfs/src/kino-1.3.4/ffmpeg " && echo "CFLAGS is $CFLAGS"
+  echo $ARCHIVE | grep udev-164 && export CFLAGS="$CFLAGS -Wl,-rpath-link,$HOME/ydfs/build-x86/udev-164/libudev/.libs/"
+  echo $ARCHIVE | grep gst-plugins-base-0.10.35 && export CFLAGS="$CFLAGS -Wl,-rpath-link,$HOME/ydfs/build-x86/gst-plugins-base-0.10.35/gst-libs/gst/interfaces/.libs/"
   echo $ARCHIVE | grep minetest && export LDFLAGS="$LDFLAGS -lIrrlicht" 
   echo $ARCHIVE | grep dolphin && export CXXFLAGS="$CXXFLAGS "$( pkg-config --cflags gtk+-2.0)
   echo $ARCHIVE | grep ffmpeg-2 && export LDFLAGS="$LDFLAGS -fPIC" && export CFLAGS="$CFLAGS -fPIC" 
@@ -268,22 +268,22 @@ fi
   . $HOME_DIBAB/scripts/includes/build-options
 
 
-	echo $ARCHIVE | grep zlib && unset LC_CONFIGURE_OPTS && LCARCHIVE_CHOICE=installfromsrc db-lcarchive $HOME/dibab/tarballs/`basename $ARCHIVE` && continue
+	echo $ARCHIVE | grep zlib && unset LC_CONFIGURE_OPTS && LCARCHIVE_CHOICE=installfromsrc db-lcarchive $HOME/ydfs/tarballs/`basename $ARCHIVE` && continue
 
 	# Build now
 
-	echo "Running db-lcarchive $HOME/dibab/tarballs/$(basename $ARCHIVE)"
-	DBKVER=$KERNEL3 LC_CONFIGURE_OPTS="$LC_CONFIGURE_OPTS" LCARCHIVE_CHOICE=installfromsrc db-lcarchive $HOME/dibab/tarballs/`basename $ARCHIVE` || touch $HOME/dibab-error
+	echo "Running db-lcarchive $HOME/ydfs/tarballs/$(basename $ARCHIVE)"
+	DBKVER=$KERNEL3 LC_CONFIGURE_OPTS="$LC_CONFIGURE_OPTS" LCARCHIVE_CHOICE=installfromsrc db-lcarchive $HOME/ydfs/tarballs/`basename $ARCHIVE` || touch $HOME/ydfs-error
        
-	[ -e $HOME/dibab-error ] && echo "Exit db-lcarchive $ARCHIVE " && tail -100 $(cat $HOME/dibab/.last-error) && echo -n "full log is " && cat $HOME/dibab/.last-error && break
+	[ -e $HOME/ydfs-error ] && echo "Exit db-lcarchive $ARCHIVE " && tail -100 $(cat $HOME/ydfs/.last-error) && echo -n "full log is " && cat $HOME/ydfs/.last-error && break
 	
 	# Build twice
 
 	if [ "$BUILD_TWICE" = "yes" ] 
 	then
 	  echo "Building twice" # && read key
-	  LC_CONFIGURE_OPTS="$LC_CONFIGURE_OPTS" LCARCHIVE_CHOICE=installfromsrc db-lcarchive $HOME/dibab/tarballs/`basename $ARCHIVE` || touch $HOME/dibab-error
-    [ -e $HOME/dibab-error ] && echo "Exit $ARCHIVE " && break
+	  LC_CONFIGURE_OPTS="$LC_CONFIGURE_OPTS" LCARCHIVE_CHOICE=installfromsrc db-lcarchive $HOME/ydfs/tarballs/`basename $ARCHIVE` || touch $HOME/ydfs-error
+    [ -e $HOME/ydfs-error ] && echo "Exit $ARCHIVE " && break
 	  unset BUILD_TWICE
 	fi
         
@@ -297,25 +297,25 @@ fi
 	echo $ARCHIVE | grep glibc && unset MAKE_INSTALL
 	echo $ARCHIVE | grep mysql-5 && install -d  $MYPREFIX/include/mysql && cp $MYPREFIX/include/errmsg.h $MYPREFIX/include/mysql/ && cp $MYPREFIX/include/mysql.h  $MYPREFIX/include/mysql/
 	echo $ARCHIVE | grep Linux-PAM && [ ! -e $HOME/$MODULE/include/security ] && ln -s $HOME/$MODULE/include/ $HOME/$MODULE/include/security
-	echo $ARCHIVE | grep netpbm && [ ! -e $DIBAB_PREFIX/$MODULE/bin/pnmtops ] && cd $HOME/dibab/src/netpbm* && make package pkgdir=/tmp/netpbm && cp -fR /tmp/netpbm/* $DIBAB_PREFIX/$MODULE/
+	echo $ARCHIVE | grep netpbm && [ ! -e $DIBAB_PREFIX/$MODULE/bin/pnmtops ] && cd $HOME/ydfs/src/netpbm* && make package pkgdir=/tmp/netpbm && cp -fR /tmp/netpbm/* $DIBAB_PREFIX/$MODULE/
 done
 
-[ -e $HOME/dibab-error ] && exit 1
+[ -e $HOME/ydfs-error ] && exit 1
 
 if [ ! -e $HOME/$ARCH/share/fonts/dejavu-fonts-ttf-2.29 ] && [ "$ARCH" != "arm" ]
 then
   install -d $HOME/$ARCH/share
-  [ ! -e $HOME/dibab/tarballs/dejavu-fonts-ttf-2.29.tar.bz2 ] && wget --directory-prefix=$HOME/dibab/tarballs http://freefr.dl.sourceforge.net/sourceforge/dejavu/dejavu-fonts-ttf-2.29.tar.bz2
-  tar xjvf $HOME/dibab/tarballs/dejavu-fonts-ttf-2.29.tar.bz2
+  [ ! -e $HOME/ydfs/tarballs/dejavu-fonts-ttf-2.29.tar.bz2 ] && wget --directory-prefix=$HOME/ydfs/tarballs http://freefr.dl.sourceforge.net/sourceforge/dejavu/dejavu-fonts-ttf-2.29.tar.bz2
+  tar xjvf $HOME/ydfs/tarballs/dejavu-fonts-ttf-2.29.tar.bz2
   mv dejavu-fonts-ttf-2.29 $HOME/$ARCH/share/fonts
 fi
 
 if [ ! -e $HOME/$ARCH/share/fonts/truetype/ukai ]
 then
-  [ ! -e $HOME/dibab/tarballs/ttf-arphic-ukai_0.2.20080216.1.orig.tar.gz ] && wget --directory-prefix=$HOME/dibab/tarballs  http://us.archive.ubuntu.com/ubuntu/pool/main/t/ttf-arphic-ukai/ttf-arphic-ukai_0.2.20080216.1.orig.tar.gz
+  [ ! -e $HOME/ydfs/tarballs/ttf-arphic-ukai_0.2.20080216.1.orig.tar.gz ] && wget --directory-prefix=$HOME/ydfs/tarballs  http://us.archive.ubuntu.com/ubuntu/pool/main/t/ttf-arphic-ukai/ttf-arphic-ukai_0.2.20080216.1.orig.tar.gz
   mkdir ukai
   cd ukai
-  tar xzvf $HOME/dibab/tarballs/ttf-arphic-ukai_0.2.20080216.1.orig.tar.gz
+  tar xzvf $HOME/ydfs/tarballs/ttf-arphic-ukai_0.2.20080216.1.orig.tar.gz
   install -v -d -m755 $HOME/$ARCH/share/fonts/truetype/ukai
   cp *.ttc fonts.* $HOME/$ARCH/share/fonts/truetype/ukai
   cp *.conf $HOME/$ARCH/etc/fonts/conf.avail/
@@ -325,10 +325,10 @@ fi
 
 if [ ! -e $HOME/$ARCH/share/fonts/truetype/uming ]
 then
-  [ ! -e $HOME/dibab/tarballs/ttf-arphic-uming_0.2.20080216.1.orig.tar.gz ] && wget --directory-prefix=$HOME/dibab/tarballs http://us.archive.ubuntu.com/ubuntu/pool/main/t/ttf-arphic-uming/ttf-arphic-uming_0.2.20080216.1.orig.tar.gz
+  [ ! -e $HOME/ydfs/tarballs/ttf-arphic-uming_0.2.20080216.1.orig.tar.gz ] && wget --directory-prefix=$HOME/ydfs/tarballs http://us.archive.ubuntu.com/ubuntu/pool/main/t/ttf-arphic-uming/ttf-arphic-uming_0.2.20080216.1.orig.tar.gz
   mkdir uming
   cd uming
-  tar xzvf $HOME/dibab/tarballs/ttf-arphic-uming_0.2.20080216.1.orig.tar.gz
+  tar xzvf $HOME/ydfs/tarballs/ttf-arphic-uming_0.2.20080216.1.orig.tar.gz
   install -v -d -m755 $HOME/$ARCH/share/fonts/truetype/uming
   cp *.ttc fonts.* $HOME/$ARCH/share/fonts/truetype/uming
   cp *.conf $HOME/$ARCH/etc/fonts/conf.avail/
@@ -345,4 +345,4 @@ done
 [ ! -e $HOME/$MODULE/buildok ] && touch $HOME/$MODULE/buildok # usefull to know which file can be wrotten into $HOME/$MODULE/ after last package build
 echo "Build packages OK"
 
-#/home/yann/x86/bin/mksquashfs /home/dibab-32/games/ /home/dibab-32/dibab/build/modules/games-x86.squashfs
+#/home/yann/x86/bin/mksquashfs /home/ydfs-32/games/ /home/ydfs-32/ydfs/build/modules/games-x86.squashfs
diff --git a/2.5/packages/db-lcarchive b/2.5/packages/db-lcarchive
--- a/2.5/packages/db-lcarchive
+++ b/2.5/packages/db-lcarchive
@@ -4,14 +4,14 @@
 
 build_the_archive()
 {  
-  echo $PWD/dibab-error > $HOME/dibab/.last-error
-  echo $PWD/dibab-log > $HOME/dibab/.last-log
+  echo $PWD/ydfs-error > $HOME/ydfs/.last-error
+  echo $PWD/ydfs-log > $HOME/ydfs/.last-log
   if [ "$MODULE" = "opkg" ] || [ "$BUILDME" = "OK" ] || [ "$DIBAB_VERBOSE_BUILD" = "YES" ] || echo $PWD | grep x11-xserver-utils
   then
   db-autobuild $MYPREFIX || exit $?
   else
-  echo -n "Log in $PWD/dibab-log , Error in $PWD/dibab-error , Building in progress.... "     
-  db-autobuild $MYPREFIX 2>dibab-error 1>dibab-log || exit $?
+  echo -n "Log in $PWD/ydfs-log , Error in $PWD/ydfs-error , Building in progress.... "     
+  db-autobuild $MYPREFIX 2>ydfs-error 1>ydfs-log || exit $?
   echo "OK"
   fi
 }
@@ -22,7 +22,7 @@ then
 fi
 
 #création et initialisation du répertoire temporaire
-install -d /$HOME/dibab/tmp
+install -d /$HOME/ydfs/tmp
 
 FILE=$1
 if [ -n "`echo $1 | grep ftp`" ] || [ -n "`echo $1 | grep http`" ]
@@ -30,13 +30,13 @@ then
   #si c'est un .dsc(Debian source) alors
   if [ -n "`echo $1 | grep '.dsc'`" ] 
   then
-    # FIXME [ -e $HOME/dibab/tarballs/`basename $1` ] && echo -n "$HOME/dibab/tarballs/`basename $1` exists" && exit 0
+    # FIXME [ -e $HOME/ydfs/tarballs/`basename $1` ] && echo -n "$HOME/ydfs/tarballs/`basename $1` exists" && exit 0
     db-build-debian-dsc $1 || exit 1
     exit 0
   fi
   #sinon, on le télécharge par wget+initialisations et changement de répertoire
   echo "wget $1 inside $0"
-  install -d $HOME/dibab/tarballs && cd $HOME/dibab/tarballs && FILE=$PWD/`basename $1` && [ ! -e `basename $1` ] && wget $1
+  install -d $HOME/ydfs/tarballs && cd $HOME/ydfs/tarballs && FILE=$PWD/`basename $1` && [ ! -e `basename $1` ] && wget $1
 fi
 
 if [ -n "$LCARCHIVE_CHOICE" ]
@@ -119,31 +119,31 @@ echo "$FILE" |grep  "pa_stable" && DIR2=portaudio && FORCED=1
 case "$ARCHIVE" in
   RUN)
     echo "$FILE"  
-        [ -e $HOME/dibab/src/$DIR/buildok-$ARCH ] && exit 0
-	# [ -e $HOME/dibab/src/$DIR/nvidia.ko ] && echo Build && exit 0
-	if [ ! -e $HOME/dibab/src/$DIR/nvidia.ko ]
+        [ -e $HOME/ydfs/src/$DIR/buildok-$ARCH ] && exit 0
+	# [ -e $HOME/ydfs/src/$DIR/nvidia.ko ] && echo Build && exit 0
+	if [ ! -e $HOME/ydfs/src/$DIR/nvidia.ko ]
         then
-	cd $HOME/dibab/src/linux-$KERNEL3/
+	cd $HOME/ydfs/src/linux-$KERNEL3/
 	make mrproper
 	cp ../../build/linux-$ARCH-$KERNEL3/.config .
 	make oldconfig && make prepare
 	make init || exit $?
 	fi
-      cd $HOME/dibab/src/
+      cd $HOME/ydfs/src/
       [ ! -e $DIR ] && sh $FILE --extract-only
       cd $DIR
       if [ ! -e nvidia.ko ]
       then
         cd kernel
-        make SYSSRC="$HOME/dibab/src/linux-$KERNEL3/" module || exit $?
+        make SYSSRC="$HOME/ydfs/src/linux-$KERNEL3/" module || exit $?
         mv nvidia.ko ..
         cd ..
       fi
       rm -fR kernel
-      install -d $HOME/dibab/packages-$ARCH/$DIR/usr/$DIR
-      cp -fR * $HOME/dibab/packages-$ARCH/$DIR/usr/$DIR
+      install -d $HOME/ydfs/packages-$ARCH/$DIR/usr/$DIR
+      cp -fR * $HOME/ydfs/packages-$ARCH/$DIR/usr/$DIR
       touch buildok-$ARCH
-      cd $HOME/dibab/packages-$ARCH/$DIR
+      cd $HOME/ydfs/packages-$ARCH/$DIR
       $HOME_DIBAB/scripts/make_opkg ||exit $?
       exit 0
     ;;
@@ -158,14 +158,14 @@ case "$ARCHIVE" in
   TARGZ)
     if [ "$CHOICE" = "installfromsrc" ]
     then
-      install -d $HOME/dibab/src/
-      cd $HOME/dibab/src/
+      install -d $HOME/ydfs/src/
+      cd $HOME/ydfs/src/
       if [ ! -e $DIR2 ]
       then
         echo $FILE
-        tar xzvf "$FILE" 1> $HOME/dibab/tmp/tar.$$.log || exit $?
+        tar xzvf "$FILE" 1> $HOME/ydfs/tmp/tar.$$.log || exit $?
       fi
-      [ ! -e $DIR2 ] && echo "ERROR : What DIR2 for $FILE ? " && sleep 1 && DIR2=`cat /$HOME/dibab/tmp/tar.$$.log | cut -d'/' -f1 | sort -u` && install -d $HOME_DIBAB/data/fixdirs && echo "DIR2=$DIR2 && FORCED=1" > $HOME_DIBAB/data/fixdirs/$(basename $FILE) && git add $HOME_DIBAB/data/fixdirs/$(basename $FILE)
+      [ ! -e $DIR2 ] && echo "ERROR : What DIR2 for $FILE ? " && sleep 1 && DIR2=`cat /$HOME/ydfs/tmp/tar.$$.log | cut -d'/' -f1 | sort -u` && install -d $HOME_DIBAB/data/fixdirs && echo "DIR2=$DIR2 && FORCED=1" > $HOME_DIBAB/data/fixdirs/$(basename $FILE) && git add $HOME_DIBAB/data/fixdirs/$(basename $FILE)
       cd $DIR2
       export DIR2=$DIR2
       export MYPREFIX=$MYPREFIX
@@ -176,20 +176,20 @@ case "$ARCHIVE" in
   ZIP)
     if [ "$CHOICE" = "installfromsrc" ]
     then
-      install -d $HOME/dibab/src/
-      cd $HOME/dibab/src/
+      install -d $HOME/ydfs/src/
+      cd $HOME/ydfs/src/
       #echo "$FILE" |grep  "wxWidgets-3" && DIR2="wxWidgets-3" && install -d $DIR2 && cd $DIR2
       echo "$FILE" |grep  "wxWidgets-3" && DIR2="wxWidgets"
-      [ ! -e $DIR2 ] && unzip -o "$FILE" 1>/$HOME/dibab/tmp/zip.$$.log && tail -10 /$HOME/dibab/tmp/zip.$$.log
+      [ ! -e $DIR2 ] && unzip -o "$FILE" 1>/$HOME/ydfs/tmp/zip.$$.log && tail -10 /$HOME/ydfs/tmp/zip.$$.log
       if [ "$DIR2" = "amd-driver-installer-catalyst-13.1-legacy-linux-x86.x86_64" ]
       then
-        DESTDIR=$HOME/dibab/packages-$ARCH/$MYDIR $HOME_DIBAB/scripts/install-catalyst13.sh || exit $?
-        cd $HOME/dibab/packages-$ARCH/catalyst13
+        DESTDIR=$HOME/ydfs/packages-$ARCH/$MYDIR $HOME_DIBAB/scripts/install-catalyst13.sh || exit $?
+        cd $HOME/ydfs/packages-$ARCH/catalyst13
         $HOME_DIBAB/scripts/make_opkg || exit $?
         exit 0
       fi
-      # [ ! -e $DIR2 ] && DIR2=`cat $HOME/dibab/tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
-      [ ! -e $DIR2 ] && echo "ERROR : What DIR2 for $FILE ? " && sleep 1 && DIR2=`cat /$HOME/dibab/tmp/zip.$$.log  | cut -d':' -f2 | cut -d'/' -f1 | sort -u | tac | head -1`
+      # [ ! -e $DIR2 ] && DIR2=`cat $HOME/ydfs/tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
+      [ ! -e $DIR2 ] && echo "ERROR : What DIR2 for $FILE ? " && sleep 1 && DIR2=`cat /$HOME/ydfs/tmp/zip.$$.log  | cut -d':' -f2 | cut -d'/' -f1 | sort -u | tac | head -1`
       cd $DIR2
       export DIR2
       export MYPREFIX=$MYPREFIX
@@ -204,12 +204,12 @@ case "$ARCHIVE" in
   DEB)
     install -d "$DIR" && cd "$DIR"
     PKGNAME=`basename $DIR|cut -d'+' -f1`
-    #if [ ! -e $HOME/dibab/packages-$ARCH/$PKGNAME ]
-    if [ ! -e $HOME/dibab/packages-$ARCH/$PKGNAME ]
+    #if [ ! -e $HOME/ydfs/packages-$ARCH/$PKGNAME ]
+    if [ ! -e $HOME/ydfs/packages-$ARCH/$PKGNAME ]
     then
-      install -d $HOME/dibab/packages-$ARCH/$PKGNAME
-      dpkg -x "$FILE" $HOME/dibab/packages-$ARCH/$PKGNAME
-      cd $HOME/dibab/packages-$ARCH/$PKGNAME
+      install -d $HOME/ydfs/packages-$ARCH/$PKGNAME
+      dpkg -x "$FILE" $HOME/ydfs/packages-$ARCH/$PKGNAME
+      cd $HOME/ydfs/packages-$ARCH/$PKGNAME
       $HOME_DIBAB/scripts/make_opkg || exit $?
       echo "Prefix is $MYPREFIX"
       install -d $MYPREFIX
@@ -221,10 +221,10 @@ case "$ARCHIVE" in
   SEVENZ)
     if [ "$CHOICE" = "installfromsrc" ]
     then
-      install -d $HOME/dibab/src/
-      cd $HOME/dibab/src/
-      [ ! -e $DIR2 ] && 7z x "$FILE" 1> $HOME/dibab/tmp/tar.$$.log
-      [ ! -e $DIR2 ] && DIR2=`cat $HOME/dibab/tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
+      install -d $HOME/ydfs/src/
+      cd $HOME/ydfs/src/
+      [ ! -e $DIR2 ] && 7z x "$FILE" 1> $HOME/ydfs/tmp/tar.$$.log
+      [ ! -e $DIR2 ] && DIR2=`cat $HOME/ydfs/tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
       cd $DIR2 
       export DIR2=$DIR2
       export MYPREFIX=$MYPREFIX
@@ -235,10 +235,10 @@ case "$ARCHIVE" in
   TARXZ)
     if [ "$CHOICE" = "installfromsrc" ]
     then
-      install -d $HOME/dibab/src/
-      cd $HOME/dibab/src/
-      [ ! -e $DIR2 ] && tar xJvf "$FILE" 1> $HOME/dibab/tmp/tar.$$.log
-      [ ! -e $DIR2 ] && DIR2=`cat $HOME/dibab/tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
+      install -d $HOME/ydfs/src/
+      cd $HOME/ydfs/src/
+      [ ! -e $DIR2 ] && tar xJvf "$FILE" 1> $HOME/ydfs/tmp/tar.$$.log
+      [ ! -e $DIR2 ] && DIR2=`cat $HOME/ydfs/tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
       cd $DIR2 
       export DIR2=$DIR2
       export MYPREFIX=$MYPREFIX
@@ -249,11 +249,11 @@ case "$ARCHIVE" in
   TARBZ)
     if [ "$CHOICE" = "installfromsrc" ]
     then
-      install -d $HOME/dibab/src/
-      cd $HOME/dibab/src/
+      install -d $HOME/ydfs/src/
+      cd $HOME/ydfs/src/
       echo "$FILE" |grep  "midori" && DIR2="midori" && install -d $DIR2 && cd $DIR2
-      [ ! -e $DIR2 ] && echo "tar xjvf $FILE" && tar xjvf "$FILE" 1> $HOME/dibab/tmp/tar.$$.log
-      [ ! -e $DIR2 ] && DIR2=`cat $HOME/dibab/tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
+      [ ! -e $DIR2 ] && echo "tar xjvf $FILE" && tar xjvf "$FILE" 1> $HOME/ydfs/tmp/tar.$$.log
+      [ ! -e $DIR2 ] && DIR2=`cat $HOME/ydfs/tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
       [ "$DIR2" != "midori" ] && cd $DIR2 
       export DIR2=$DIR2
       export MYPREFIX=$MYPREFIX
@@ -263,7 +263,7 @@ case "$ARCHIVE" in
     ;;
   DSC)
     export MYPREFIX=$MYPREFIX
-    # FIXME [ -e $HOME/dibab/tarballs/`basename $1` ] && echo -n "$HOME/dibab/tarballs/`basename $1` exists" && exit 0
+    # FIXME [ -e $HOME/ydfs/tarballs/`basename $1` ] && echo -n "$HOME/ydfs/tarballs/`basename $1` exists" && exit 0
     db-build-debian-dsc $1 || exit $?
     ;;
   *)
diff --git a/2.5/scripts/make_iso b/2.5/scripts/make_iso
--- a/2.5/scripts/make_iso
+++ b/2.5/scripts/make_iso
@@ -183,17 +183,17 @@ print_grub_options()
 {
   echo "timeout 5" 
   
-  echo "title Dibab " 
+  echo "title Ydfs " 
   echo "root (hd0,0)"                 
   echo "kernel /boot/$KERNEL36 $COMMON"             
   echo "initrd /boot/$INITRD26"     
   
-  echo "title Dibab  Partition 2" 
+  echo "title Ydfs  Partition 2" 
   echo "root (hd0,1)"                 
   echo "kernel /boot/$KERNEL36 $COMMON"             
   echo "initrd /boot/$INITRD26"     
   
-  echo "title Dibab  failsafe" 
+  echo "title Ydfs  failsafe" 
   echo "root (hd0,0)"                 
   echo "kernel /boot/$KERNEL36 $COMMON acpi=off noacpi noapic nocapic"             
   echo "initrd /boot/$INITRD26"     
@@ -247,10 +247,10 @@ install -d $ISOTMP/iso/modules
 if [ "$MEDIA" = "DVD" ]
 then
 install -d /$ISOTMP/iso/pkg
-ls $HOME/dibab/opkg/ | while read PKG
+ls $HOME/ydfs/opkg/ | while read PKG
 do
   echo "$PKG"
-  ln -s $HOME/dibab/opkg/$PKG /$ISOTMP/iso/pkg
+  ln -s $HOME/ydfs/opkg/$PKG /$ISOTMP/iso/pkg
 done
 fi
 
@@ -293,11 +293,11 @@ cp boot/menu.c32 /$ISOTMP/iso/isolinux
 cp boot/vesamenu.c32 /$ISOTMP/iso/isolinux
 if [ "$ARCH" = "x86" ]
 then
-cp /$HOME/dibab/build/linux-$ARCH-$KERNEL3/arch/i386/boot/bzImage /$ISOTMP/iso/isolinux/$KERNEL36 || exit 1
+cp /$HOME/ydfs/build/linux-$ARCH-$KERNEL3/arch/i386/boot/bzImage /$ISOTMP/iso/isolinux/$KERNEL36 || exit 1
 else
-cp /$HOME/dibab/build/linux-$ARCH-$KERNEL3/arch/$ARCH/boot/bzImage /$ISOTMP/iso/isolinux/$KERNEL36 || exit 1
+cp /$HOME/ydfs/build/linux-$ARCH-$KERNEL3/arch/$ARCH/boot/bzImage /$ISOTMP/iso/isolinux/$KERNEL36 || exit 1
 fi
-cp /$HOME/dibab/build-$ARCH/$INITRD26 /$ISOTMP/iso/isolinux || exit 4
+cp /$HOME/ydfs/build-$ARCH/$INITRD26 /$ISOTMP/iso/isolinux || exit 4
 
 echo "
 [autorun]
@@ -323,7 +323,7 @@ gunzip memtest86+-5.01.bin.gz || exit $?
 fi
 cp memtest86+-5.01.bin /$ISOTMP/iso/isolinux/memtest
 
-[ -e $HOME/dibab/wineprogs ] && cp -fR $HOME/dibab/wineprogs $ISOTMP/iso/
+[ -e $HOME/ydfs/wineprogs ] && cp -fR $HOME/ydfs/wineprogs $ISOTMP/iso/
 
 # For unetbootin
 cp /$ISOTMP/iso/isolinux/$INITRD26 /$ISOTMP/iso/isolinux/initramfs
@@ -374,7 +374,7 @@ done
 
 # more /$ISOTMP/iso/md5sum.txt
 
-ISONAME="Dibab-$LCBUILD"
+ISONAME="Ydfs-$LCBUILD"
 
 CPUARCH="amd64"
 [ "$ARCH" = "x86" ] && CPUARCH="i386"
diff --git a/2.5/scripts/make_linux b/2.5/scripts/make_linux
--- a/2.5/scripts/make_linux
+++ b/2.5/scripts/make_linux
@@ -1,15 +1,15 @@
 #!/bin/sh
 . ./config.ini
 
-install -d /$HOME/dibab/src/
-install -d /$HOME/dibab/tarballs/
-install -d /$HOME/dibab/build/
-cd /$HOME/dibab
+install -d /$HOME/ydfs/src/
+install -d /$HOME/ydfs/tarballs/
+install -d /$HOME/ydfs/build/
+cd /$HOME/ydfs
 if [ "$SUBARCH" = "raspi" ]
 then
   echo $SUBARCH
-  install -d $HOME/dibab/build/linux-$ARCH-"$KERNEL3"
-  BUILD_DIR=$HOME/dibab/build/linux-$ARCH-"$KERNEL3"
+  install -d $HOME/ydfs/build/linux-$ARCH-"$KERNEL3"
+  BUILD_DIR=$HOME/ydfs/build/linux-$ARCH-"$KERNEL3"
   [ ! -e tarballs/$KERNEL3.zip ] && wget --directory-prefix=tarballs https://github.com/raspberrypi/linux/archive/$KERNEL3.zip
   [ ! -e src/linux-$KERNEL3 ] && unzip tarballs/$KERNEL3.zip -d src
   cd src/linux-$KERNEL3
@@ -72,8 +72,8 @@ fi
 [ "$ARCH" = "arm" ] && [ -e drivers/tty/serial/samsung.c ] && grep "EXPORT_SYMBOL_GPL(s3c24xx_serial_remove);" drivers/tty/serial/samsung.c &&  sed -i "s@EXPORT_SYMBOL_GPL(s3c24xx_serial_remove);@@" drivers/tty/serial/samsung.c
 [ "$ARCH" = "arm" ] && [ -e drivers/serial/samsung.c ] && grep "EXPORT_SYMBOL_GPL(s3c24xx_serial_remove);" drivers/serial/samsung.c &&  sed -i "s@EXPORT_SYMBOL_GPL(s3c24xx_serial_remove);@@" drivers/serial/samsung.c
 
-install -d $HOME/dibab/build/linux-$ARCH-"$KERNEL3"
-BUILD_DIR=$HOME/dibab/build/linux-$ARCH-"$KERNEL3"
+install -d $HOME/ydfs/build/linux-$ARCH-"$KERNEL3"
+BUILD_DIR=$HOME/ydfs/build/linux-$ARCH-"$KERNEL3"
 #BUILD_DIR=.
 
 [ "$SUBARCH" = "raspi-qemu" ] && [ ! -e $BUILD_DIR/.config ] && cp $HOME_DIBAB/config/kernel-raspi-qemu/config  $BUILD_DIR/.config
@@ -109,8 +109,8 @@ git add /$HOME_DIBAB/config/kernel-$ARCH/linux-"$KERNEL3"/
   if [ $? != 0 ]
   then
     make modules O=$BUILD_DIR || exit 0
-    make modules_install O=$BUILD_DIR INSTALL_MOD_PATH=$HOME/dibab/kernel-$ARCH/modules/$KERNEL3 || exit 1
-    /sbin/depmod -b $HOME/dibab/kernel-$ARCH/modules/"$KERNEL3" -m "$KERNEL3"
-    [ ! -e $HOME/dibab/kernel-$ARCH/modules/$KERNEL3/lib/modules/"$KERNEL3"/modules.dep ] && echo "$HOME/dibab/kernel-$ARCH/modules/"$KERNEL3"/modules.dep not found" && exit 2
+    make modules_install O=$BUILD_DIR INSTALL_MOD_PATH=$HOME/ydfs/kernel-$ARCH/modules/$KERNEL3 || exit 1
+    /sbin/depmod -b $HOME/ydfs/kernel-$ARCH/modules/"$KERNEL3" -m "$KERNEL3"
+    [ ! -e $HOME/ydfs/kernel-$ARCH/modules/$KERNEL3/lib/modules/"$KERNEL3"/modules.dep ] && echo "$HOME/ydfs/kernel-$ARCH/modules/"$KERNEL3"/modules.dep not found" && exit 2
   fi
   echo buildt
