qt5

diff --git a/2.5/packages/build-packages b/2.5/packages/build-packages
--- a/2.5/packages/build-packages
+++ b/2.5/packages/build-packages
@@ -276,8 +276,12 @@ fi
 	echo "Running db-lcarchive $HOME/ydfs/tarballs/$(basename $ARCHIVE)"
 	DBKVER=$KERNEL3 LC_CONFIGURE_OPTS="$LC_CONFIGURE_OPTS" LCARCHIVE_CHOICE=installfromsrc db-lcarchive $HOME/ydfs/tarballs/`basename $ARCHIVE` || touch $HOME/ydfs-error
        
-	[ -e $HOME/ydfs-error ] && echo "Exit db-lcarchive $ARCHIVE " && tail -100 $(cat $HOME/ydfs/.last-error) && echo -n "full log is " && cat $HOME/ydfs/.last-error && break
-	
+	if [ -e $HOME/ydfs-error ]
+        then
+	   echo "Exit db-lcarchive $ARCHIVE " 
+		# [ -e $HOME/ydfs/.last-error ] && tail -100 $(cat $HOME/ydfs/.last-error) && echo -n "full log is " && cat $HOME/ydfs/.last-error && break
+		exit 1	
+	fi
 	# Build twice
 
 	if [ "$BUILD_TWICE" = "yes" ] 
