3.0 full fix

diff --git a/3.0/scripts/build_archive b/3.0/scripts/build_archive
--- a/3.0/scripts/build_archive
+++ b/3.0/scripts/build_archive
@@ -3,20 +3,20 @@
 
 build_the_archive()
 {  
-  echo $PWD/-error > $HOME//.last-error
-  echo $PWD/-log > $HOME//.last-log
+  echo $PWD/ydfs-error > $HOME/ydfs/.last-error
+  echo $PWD/ydfs-log > $HOME/ydfs/.last-log
   if [ "$MODULE" = "opkg" ] || [ "$BUILDME" = "OK" ] || [ "$DIBAB_VERBOSE_BUILD" = "YES" ] || echo $PWD | grep x11-xserver-utils
   then
   $HOME_DIBAB/scripts/build_from_source $PREFIX || exit $?
   else
-  echo -n "Log in $PWD/-log , Error in $PWD/-error , Building in progress.... "     
-  $HOME_DIBAB/scripts/build_from_source $PREFIX 2>-error 1>-log || exit $?
+  echo -n "Log in $PWD/ydfs-log , Error in $PWD/ydfs-error , Building in progress.... "     
+  $HOME_DIBAB/scripts/build_from_source $PREFIX 2>ydfs-error 1>ydfs-log || exit $?
   echo "OK"
   fi
 }
 
 #création et initialisation du répertoire temporaire
-install -d /$HOME//tmp
+install -d /$HOME/ydfs/tmp
 
 FILE=$1
 if [ -n "`echo $1 | grep ftp`" ] || [ -n "`echo $1 | grep http`" ]
@@ -24,12 +24,12 @@ then
   #si c'est un .dsc(Debian source) alors
   if [ -n "`echo $1 | grep '.dsc'`" ] 
   then
-    # FIXME [ -e $HOME//tarballs/`basename $1` ] && echo -n "$HOME//tarballs/`basename $1` exists" && exit 0
+    # FIXME [ -e $HOME/ydfs/tarballs/`basename $1` ] && echo -n "$HOME/ydfs/tarballs/`basename $1` exists" && exit 0
     db-build-debian-dsc $1 || exit 1
     exit 0
   fi
   #sinon, on le télécharge par wget+initialisations et changement de répertoire
-  install -d $HOME//tarballs && cd $HOME//tarballs && FILE=$PWD/`basename $1` && [ ! -e `basename $1` ] && wget $1
+  install -d $HOME/ydfs/tarballs && cd $HOME/ydfs/tarballs && FILE=$PWD/`basename $1` && [ ! -e `basename $1` ] && wget $1
 fi
 
 DIR=`echo $FILE |  sed 's/\.[^\.]*$//'`
@@ -102,31 +102,31 @@ echo "$FILE" |grep  "pa_stable" && DIR2=portaudio && FORCED=1
 case "$ARCHIVE" in
   RUN)
     echo "$FILE"  
-        [ -e $HOME//src/$DIR/buildok-$ARCH ] && exit 0
-	# [ -e $HOME//src/$DIR/nvidia.ko ] && echo Build && exit 0
-	if [ ! -e $HOME//src/$DIR/nvidia.ko ]
+        [ -e $HOME/ydfs/src/$DIR/buildok-$ARCH ] && exit 0
+	# [ -e $HOME/ydfs/src/$DIR/nvidia.ko ] && echo Build && exit 0
+	if [ ! -e $HOME/ydfs/src/$DIR/nvidia.ko ]
         then
-	cd $HOME//src/linux-$KERNEL3/
+	cd $HOME/ydfs/src/linux-$KERNEL3/
 	make mrproper
 	cp ../../build/linux-$ARCH-$KERNEL3/.config .
 	make oldconfig && make prepare
 	make init || exit $?
 	fi
-      cd $HOME//src/
+      cd $HOME/ydfs/src/
       [ ! -e $DIR ] && sh $FILE --extract-only
       cd $DIR
       if [ ! -e nvidia.ko ]
       then
         cd kernel
-        make SYSSRC="$HOME//src/linux-$KERNEL3/" module || exit $?
+        make SYSSRC="$HOME/ydfs/src/linux-$KERNEL3/" module || exit $?
         mv nvidia.ko ..
         cd ..
       fi
       rm -fR kernel
-      install -d $HOME//packages-$ARCH/$DIR/usr/$DIR
-      cp -fR * $HOME//packages-$ARCH/$DIR/usr/$DIR
+      install -d $HOME/ydfs/packages-$ARCH/$DIR/usr/$DIR
+      cp -fR * $HOME/ydfs/packages-$ARCH/$DIR/usr/$DIR
       touch buildok-$ARCH
-      cd $HOME//packages-$ARCH/$DIR
+      cd $HOME/ydfs/packages-$ARCH/$DIR
       $HOME_DIBAB/scripts/make_opkg ||exit $?
       exit 0
     ;;
@@ -137,48 +137,48 @@ case "$ARCHIVE" in
     gunzip "$FILE"  
     ;;
   TAR)
-      install -d $HOME//src/
-      cd $HOME//src/
+      install -d $HOME/ydfs/src/
+      cd $HOME/ydfs/src/
       if [ ! -e $DIR2 ]
       then
         echo $FILE
-        tar xvf "$FILE" 1> $HOME//tmp/tar.$$.log || exit $?
+        tar xvf "$FILE" 1> $HOME/ydfs/tmp/tar.$$.log || exit $?
       fi
-      [ ! -e $DIR2 ] && echo "ERROR : What DIR2 for $FILE ? " && sleep 1 && DIR2=`cat /$HOME//tmp/tar.$$.log | cut -d'/' -f1 | sort -u` && install -d $HOME_DIBAB/data/fixdirs && echo "DIR2=$DIR2 && FORCED=1" > $HOME_DIBAB/data/fixdirs/$(basename $FILE) && git add $HOME_DIBAB/data/fixdirs/$(basename $FILE)
+      [ ! -e $DIR2 ] && echo "ERROR : What DIR2 for $FILE ? " && sleep 1 && DIR2=`cat /$HOME/ydfs/tmp/tar.$$.log | cut -d'/' -f1 | sort -u` && install -d $HOME_DIBAB/data/fixdirs && echo "DIR2=$DIR2 && FORCED=1" > $HOME_DIBAB/data/fixdirs/$(basename $FILE) && git add $HOME_DIBAB/data/fixdirs/$(basename $FILE)
       cd $DIR2
       export DIR2=$DIR2
       export LC_CONFIGURE_OPTS="$LC_CONFIGURE_OPTS"
       build_the_archive
     ;;
   TARGZ)
-      install -d $HOME//src/
-      cd $HOME//src/
+      install -d $HOME/ydfs/src/
+      cd $HOME/ydfs/src/
       if [ ! -e $DIR2 ]
       then
         echo $FILE
-        tar xzvf "$FILE" 1> $HOME//tmp/tar.$$.log || exit $?
+        tar xzvf "$FILE" 1> $HOME/ydfs/tmp/tar.$$.log || exit $?
       fi
-      [ ! -e $DIR2 ] && echo "ERROR : What DIR2 for $FILE ? " && sleep 1 && DIR2=`cat /$HOME//tmp/tar.$$.log | cut -d'/' -f1 | sort -u` && install -d $HOME_DIBAB/data/fixdirs && echo "DIR2=$DIR2 && FORCED=1" > $HOME_DIBAB/data/fixdirs/$(basename $FILE) && git add $HOME_DIBAB/data/fixdirs/$(basename $FILE)
+      [ ! -e $DIR2 ] && echo "ERROR : What DIR2 for $FILE ? " && sleep 1 && DIR2=`cat /$HOME/ydfs/tmp/tar.$$.log | cut -d'/' -f1 | sort -u` && install -d $HOME_DIBAB/data/fixdirs && echo "DIR2=$DIR2 && FORCED=1" > $HOME_DIBAB/data/fixdirs/$(basename $FILE) && git add $HOME_DIBAB/data/fixdirs/$(basename $FILE)
       cd $DIR2
       export DIR2=$DIR2
       export LC_CONFIGURE_OPTS="$LC_CONFIGURE_OPTS"
       build_the_archive
     ;;
   ZIP)
-      install -d $HOME//src/
-      cd $HOME//src/
+      install -d $HOME/ydfs/src/
+      cd $HOME/ydfs/src/
       #echo "$FILE" |grep  "wxWidgets-3" && DIR2="wxWidgets-3" && install -d $DIR2 && cd $DIR2
       echo "$FILE" |grep  "wxWidgets-3" && DIR2="wxWidgets"
-      [ ! -e $DIR2 ] && unzip -o "$FILE" 1>/$HOME//tmp/zip.$$.log && tail -10 /$HOME//tmp/zip.$$.log
+      [ ! -e $DIR2 ] && unzip -o "$FILE" 1>/$HOME/ydfs/tmp/zip.$$.log && tail -10 /$HOME/ydfs/tmp/zip.$$.log
       if [ "$DIR2" = "amd-driver-installer-catalyst-13.1-legacy-linux-x86.x86_64" ]
       then
-        DESTDIR=$HOME//packages-$ARCH/$MYDIR $HOME_DIBAB/scripts/install-catalyst13.sh || exit $?
-        cd $HOME//packages-$ARCH/catalyst13
+        DESTDIR=$HOME/ydfs/packages-$ARCH/$MYDIR $HOME_DIBAB/scripts/install-catalyst13.sh || exit $?
+        cd $HOME/ydfs/packages-$ARCH/catalyst13
         $HOME_DIBAB/scripts/make_opkg || exit $?
         exit 0
       fi
-      # [ ! -e $DIR2 ] && DIR2=`cat $HOME//tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
-      [ ! -e $DIR2 ] && echo "ERROR : What DIR2 for $FILE ? " && sleep 1 && DIR2=`cat /$HOME//tmp/zip.$$.log  | cut -d':' -f2 | cut -d'/' -f1 | sort -u | tac | head -1`
+      # [ ! -e $DIR2 ] && DIR2=`cat $HOME/ydfs/tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
+      [ ! -e $DIR2 ] && echo "ERROR : What DIR2 for $FILE ? " && sleep 1 && DIR2=`cat /$HOME/ydfs/tmp/zip.$$.log  | cut -d':' -f2 | cut -d'/' -f1 | sort -u | tac | head -1`
       cd $DIR2
       export DIR2
       export LC_CONFIGURE_OPTS="$LC_CONFIGURE_OPTS"
@@ -191,12 +191,12 @@ case "$ARCHIVE" in
   DEB)
     install -d "$DIR" && cd "$DIR"
     PKGNAME=`basename $DIR|cut -d'+' -f1`
-    #if [ ! -e $HOME//packages-$ARCH/$PKGNAME ]
-    if [ ! -e $HOME//packages-$ARCH/$PKGNAME ]
+    #if [ ! -e $HOME/ydfs/packages-$ARCH/$PKGNAME ]
+    if [ ! -e $HOME/ydfs/packages-$ARCH/$PKGNAME ]
     then
-      install -d $HOME//packages-$ARCH/$PKGNAME
-      dpkg -x "$FILE" $HOME//packages-$ARCH/$PKGNAME
-      cd $HOME//packages-$ARCH/$PKGNAME
+      install -d $HOME/ydfs/packages-$ARCH/$PKGNAME
+      dpkg -x "$FILE" $HOME/ydfs/packages-$ARCH/$PKGNAME
+      cd $HOME/ydfs/packages-$ARCH/$PKGNAME
       $HOME_DIBAB/scripts/make_opkg || exit $?
       echo "Prefix is $PREFIX"
       install -d $PREFIX
@@ -206,38 +206,38 @@ case "$ARCHIVE" in
   RAR)
     ;;
   SEVENZ)
-      install -d $HOME//src/
-      cd $HOME//src/
-      [ ! -e $DIR2 ] && 7z x "$FILE" 1> $HOME//tmp/tar.$$.log
-      [ ! -e $DIR2 ] && DIR2=`cat $HOME//tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
+      install -d $HOME/ydfs/src/
+      cd $HOME/ydfs/src/
+      [ ! -e $DIR2 ] && 7z x "$FILE" 1> $HOME/ydfs/tmp/tar.$$.log
+      [ ! -e $DIR2 ] && DIR2=`cat $HOME/ydfs/tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
       cd $DIR2 
       export DIR2=$DIR2
       export LC_CONFIGURE_OPTS="$LC_CONFIGURE_OPTS"
       build_the_archive
     ;;
   TARXZ)
-      install -d $HOME//src/
-      cd $HOME//src/
-      [ ! -e $DIR2 ] && tar xJvf "$FILE" 1> $HOME//tmp/tar.$$.log
-      [ ! -e $DIR2 ] && DIR2=`cat $HOME//tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
+      install -d $HOME/ydfs/src/
+      cd $HOME/ydfs/src/
+      [ ! -e $DIR2 ] && tar xJvf "$FILE" 1> $HOME/ydfs/tmp/tar.$$.log
+      [ ! -e $DIR2 ] && DIR2=`cat $HOME/ydfs/tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
       cd $DIR2 
       export DIR2=$DIR2
       export LC_CONFIGURE_OPTS="$LC_CONFIGURE_OPTS"
       build_the_archive
     ;;
   TARBZ)
-      install -d $HOME//src/
-      cd $HOME//src/
+      install -d $HOME/ydfs/src/
+      cd $HOME/ydfs/src/
       echo "$FILE" |grep  "midori" && DIR2="midori" && install -d $DIR2 && cd $DIR2
-      [ ! -e $DIR2 ] && echo "tar xjvf $FILE" && tar xjvf "$FILE" 1> $HOME//tmp/tar.$$.log
-      [ ! -e $DIR2 ] && DIR2=`cat $HOME//tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
+      [ ! -e $DIR2 ] && echo "tar xjvf $FILE" && tar xjvf "$FILE" 1> $HOME/ydfs/tmp/tar.$$.log
+      [ ! -e $DIR2 ] && DIR2=`cat $HOME/ydfs/tmp/tar.$$.log | cut -d'/' -f1 | sort -u`
       [ "$DIR2" != "midori" ] && cd $DIR2 
       export DIR2=$DIR2
       export LC_CONFIGURE_OPTS="$LC_CONFIGURE_OPTS"
       build_the_archive
     ;;
   DSC)
-    # FIXME [ -e $HOME//tarballs/`basename $1` ] && echo -n "$HOME//tarballs/`basename $1` exists" && exit 0
+    # FIXME [ -e $HOME/ydfs/tarballs/`basename $1` ] && echo -n "$HOME/ydfs/tarballs/`basename $1` exists" && exit 0
     db-build-debian-dsc $1 || exit $?
     ;;
   *)
diff --git a/3.0/scripts/build_core b/3.0/scripts/build_core
--- a/3.0/scripts/build_core
+++ b/3.0/scripts/build_core
@@ -7,12 +7,12 @@ export TMPDIR=$HOME/tmp
 install -d $HOME/tmp
 install -d $HOME/$CARCH/share/aclocal
 [ ! -e $HOME/$MODULE/share/aclocal ] && install -d $HOME/$MODULE/share/aclocal
-install -d $HOME//src
-install -d $HOME//tarballs
+install -d $HOME/ydfs/src
+install -d $HOME/ydfs/tarballs
 
-install -d $HOME//CFLAGS
-install -d $HOME//CPPFLAGS
-install -d $HOME//CPPFLAGS
+install -d $HOME/ydfs/CFLAGS
+install -d $HOME/ydfs/CPPFLAGS
+install -d $HOME/ydfs/CPPFLAGS
 
 [ "$CARCH" = "x86_64" ] && [ ! -e $HOME/$CARCH/lib64 ] && install -d $HOME/$CARCH/lib && ln -s $HOME/$CARCH/lib $HOME/$CARCH/lib64
 
@@ -25,7 +25,7 @@ unset CLEARENV XDG_DATA_DIRS PKG_CONFIG_PATH CFLAGS CXXFLAGS CPPFLAGS LDFLAGS LD
 
 # $1 est supposée être une ISO particulière demandée passée en paramètre, lanpower, par exemple: pourquoi est-ce "uclib" ici ? 
 # Sinon, La ligne 14 "echo $SRC_PATH/list-$1" donne n'importe quoi
-[ "$1" = "uclib" ] && export CC=$HOME//x-tools/i386-unknown-linux-uclibc/bin/i386-unknown-linux-uclibc-gcc
+[ "$1" = "uclib" ] && export CC=$HOME/ydfs/x-tools/i386-unknown-linux-uclibc/bin/i386-unknown-linux-uclibc-gcc
 # initialisation du chemin pour le compilateur C x86
 [ "$CARCH" = "x86" ] && [ "$CC" = "" ] && export CC=`which gcc`
 
@@ -37,9 +37,9 @@ export ACLOCAL_FLAGS=" -I $HOME/$MODULE/share/aclocal/  -I $HOME/$CARCH/share/ac
 # initialisations des variables utilisées 
 export CXX="g++"
 export CMAKE_LIBRARY_PATH=$CMAKE_LIBRARY_PATH:/$HOME/$MODULE/lib:$HOME/$CARCH/lib CMAKE_INCLUDE_PATH=$CMAKE_INCLUDE_PATH:$HOME/$MODULE/include:$HOME/$CARCH/include
-export CFLAGS="$CFLAGS -O2 -I. -I""$HOME/$MODULE/include -I$HOME//CFLAGS"
-export CPPFLAGS="$CPPFLAGS -I""$HOME/$MODULE/include -I$HOME//CPPFLAGS"
-export CXXFLAGS="$CXXFLAGS -I""$HOME/$MODULE/include -I$HOME//CXXFLAGS"
+export CFLAGS="$CFLAGS -O2 -I. -I""$HOME/$MODULE/include -I$HOME/ydfs/CFLAGS"
+export CPPFLAGS="$CPPFLAGS -I""$HOME/$MODULE/include -I$HOME/ydfs/CPPFLAGS"
+export CXXFLAGS="$CXXFLAGS -I""$HOME/$MODULE/include -I$HOME/ydfs/CXXFLAGS"
 export CXXFLAGS="$CXXFLAGS -I""$HOME/$CARCH/include"
 export CXXFLAGS="$CXXFLAGS -I""$HOME/$CARCH/include/AL"
 export CXXFLAGS="$CXXFLAGS -I""$HOME/$CARCH/irrlicht"
@@ -48,7 +48,7 @@ export LDFLAGS="$LDFLAGS -L""$HOME/$MODULE/lib "
 export LDFLAGS="$LDFLAGS -L""$HOME/$MODULE/lib64 "
 export GTKMM_BASEPATH=$HOME/$CARCH
 # autres initialisations selon les architectures(processeurs)
-[ "$CARCH" = "arm" ] && export LDFLAGS="$LDFLAGS -Wl,-rpath-link,$HOME/$CARCH/lib -Wl,-rpath-link,/home/raspi//tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/lib" # FIXME
+[ "$CARCH" = "arm" ] && export LDFLAGS="$LDFLAGS -Wl,-rpath-link,$HOME/$CARCH/lib -Wl,-rpath-link,/home/raspi/ydfs/tools-master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/lib" # FIXME
 [ "$CARCH" = "x86" ] && export LDFLAGS="$LDFLAGS -Wl,-rpath-link,$HOME/$MODULE/lib"
 [ "$CARCH" = "x86_64" ] && export LDFLAGS="$LDFLAGS -Wl,-rpath-link,$HOME/$MODULE/lib64 -Wl,-rpath-link,$HOME/$MODULE/lib"
 export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/$MODULE/lib"
@@ -63,7 +63,7 @@ PATH=$PWD:$PATH
 else
 PATH=$PWD:$HOME/Qt5/5.4/gcc/bin:$MODULEPATH:$PATH:
 fi
-PATH=$HOME//llvm-clang/bin/:$PATH
+PATH=$HOME/ydfs/llvm-clang/bin/:$PATH
 # build tar
 whoami | grep root && export FORCE_UNSAFE_CONFIGURE=1
 
@@ -75,7 +75,7 @@ export PYTHON_PREFIX=$DIBAB_PREFIX/$MODULE/
 export LIB_CUPS=$DIBAB_PREFIX/$CARCH/lib
 export CUPS_ETC=$DIBAB_PREFIX/$CARCH/etc
 
-[ -e $HOME/-error ] && rm $HOME/-error
+[ -e $HOME/ydfs-error ] && rm $HOME/ydfs-error
 
 #$HOME_DIBAB/scripts/first-env
 LIST=$SRC_PATH/$MODULE.list
@@ -107,7 +107,7 @@ do
   if [  -n "`echo $PKGURL | grep 'archsource:'`" ] 
 then
   PKG=`echo $PKGURL | cut -d':' -f2`
-  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME//packages/$PKG ] && echo "$HOME//packages/$PKG exists" && continue
+  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME/ydfs/packages/$PKG ] && echo "$HOME/ydfs/packages/$PKG exists" && continue
   $HOME_DIBAB/scripts/get-archpkg $PKG
   $HOME_DIBAB/scripts/build-archpkg || exit $?
   exit 0
@@ -115,7 +115,7 @@ fi
   if [  -n "`echo $PKGURL | grep 'archlinuxpatched:'`" ] 
 then
   PKG=`echo $PKGURL | cut -d':' -f2`
-  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME//packages/$PKG ] && echo "$HOME//packages/$PKG exists" && continue
+  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME/ydfs/packages/$PKG ] && echo "$HOME/ydfs/packages/$PKG exists" && continue
   $HOME_DIBAB/scripts/get-archpkg $PKG
   PKGURL=`$HOME_DIBAB/scripts/echo-archpkg $PKG`
   echo "Arch linux source for $PKG : $PKGURL_URL"
@@ -123,14 +123,14 @@ fi
   if [  -n "`echo $PKGURL | grep 'archlinux:'`" ] 
 then
   PKG=`echo $PKGURL | cut -d':' -f2`
-  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME//packages/$PKG ] && echo "$HOME//packages/$PKG exists" && continue
+  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME/ydfs/packages/$PKG ] && echo "$HOME/ydfs/packages/$PKG exists" && continue
   PKGURL=`$HOME_DIBAB/scripts/echo-archpkg $PKG`
   echo "Arch linux source for $PKG : $PKGURL_URL"
 fi
   PKGNAME=$(basename $PKGURL_URL | cut -d'-' -f1)
-  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME//packages/$PKGNAME ] && echo "$HOME//packages/$PKGNAME exists" && continue
+  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME/ydfs/packages/$PKGNAME ] && echo "$HOME/ydfs/packages/$PKGNAME exists" && continue
   DIRNAME=`basename $PKGURL_URL |sed "s/.tar.xz//" | sed "s/.tar.bz2//" | sed "s/.tar.gz//"`
-  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME//src/$DIRNAME/distinstall.done ] && echo "distinstall.done" && continue
+  [ "$FORCEBUILD" != "OK" ] && [ -e $HOME/ydfs/src/$DIRNAME/distinstall.done ] && echo "distinstall.done" && continue
   FIRST=`echo $PKGURL | head -c1`
   [ "$FIRST" = '#' ] && continue
   PKGURL=`echo $PKGURL|cut -d'#' -f1`
@@ -141,7 +141,7 @@ fi
   export PREFIX=$DIBAB_PREFIX/$MODULE/
   if [  -n "`echo $PKGURL | grep 'svn://'`" ] 
   then
-    cd $HOME//src
+    cd $HOME/ydfs/src
     SOURCE_DIR=`basename $PKGURL | cut -d'.' -f1`
     [ ! -e $SOURCE_DIR ] && svn co $PKGURL
     cd $SOURCE_DIR
@@ -151,52 +151,52 @@ fi
   fi
   if [  -n "`echo $PKGURL | grep 'lp:'`" ] 
   then
-    cd $HOME//src
+    cd $HOME/ydfs/src
     SOURCE_DIR=`echo $PKGURL | cut -d':' -f2`
     [ ! -e $SOURCE_DIR ] && bzr checkout --lightweight $PKGURL
     cd $SOURCE_DIR
-    $HOME_DIBAB/scripts/build_from_source $DIBAB_PREFIX/$MODULE || touch $HOME/-error
-    [ -e $HOME/-error ] && echo "Exit $PKGURL " && break
+    $HOME_DIBAB/scripts/build_from_source $DIBAB_PREFIX/$MODULE || touch $HOME/ydfs-error
+    [ -e $HOME/ydfs-error ] && echo "Exit $PKGURL " && break
     continue
   fi
   if [  -n "`echo $PKGURL | grep 'git://'`" ] || [  -n "`echo $PKGURL | grep 'opkg-gtk2.git'`" ] 
   then
-    cd $HOME//src
+    cd $HOME/ydfs/src
     SOURCE_DIR=`basename $PKGURL | cut -d'.' -f1`
     [ ! -e $SOURCE_DIR ] && git clone $PKGURL
     cd $SOURCE_DIR
-    $HOME_DIBAB/scripts/build_from_source $DIBAB_PREFIX/$MODULE || touch $HOME/-error
-    [ -e $HOME/-error ] && echo "Exit $PKGURL " && break
+    $HOME_DIBAB/scripts/build_from_source $DIBAB_PREFIX/$MODULE || touch $HOME/ydfs-error
+    [ -e $HOME/ydfs-error ] && echo "Exit $PKGURL " && break
     continue
   fi
   if [  -n "`echo $PKGURL | grep 'CPAN:/'`" ] 
   then
     modperl=`echo $PKGURL | cut -d '/' -f2` 
     echo "Run  db-build-modperl $modperl" 
-	  SDL_INC=$HOME/$CARCH/include SDL_LIB=$HOME/$CARCH/lib db-build-modperl $modperl || touch $HOME/-error
-    [ -e $HOME/-error ] && echo "Exit $PKGURL " && break
+	  SDL_INC=$HOME/$CARCH/include SDL_LIB=$HOME/$CARCH/lib db-build-modperl $modperl || touch $HOME/ydfs-error
+    [ -e $HOME/ydfs-error ] && echo "Exit $PKGURL " && break
     continue
   fi
-  if [ -e $HOME//tarballs/`basename $PKGURL` ]
+  if [ -e $HOME/ydfs/tarballs/`basename $PKGURL` ]
   then
-    test -s $HOME//tarballs/`basename $PKGURL` || rm $HOME//tarballs/`basename $PKGURL`
+    test -s $HOME/ydfs/tarballs/`basename $PKGURL` || rm $HOME/ydfs/tarballs/`basename $PKGURL`
   fi
-  [ -e $HOME//tarballs/`basename $PKGURL`.start ] && [ -e $HOME//tarballs/`basename $PKGURL` ] && rm $HOME//tarballs/`basename $PKGURL`
-  [ ! -e $HOME//tarballs/`basename $PKGURL` ] && touch $HOME//tarballs/`basename $PKGURL`.start && echo "Get $PKGURL" && wget --trust-server-name --tries=5 -w 6 --no-check-certificate --output-document=$HOME//tarballs/`basename $PKGURL` $PKGURL && rm $HOME//tarballs/`basename $PKGURL`.start
-  test -s $HOME//tarballs/`basename $PKGURL` || rm $HOME//tarballs/`basename $PKGURL`
-  [ ! -e $HOME//tarballs/`basename $PKGURL` ] && echo "`basename $PKGURL` not found " && touch $HOME/-error
-  [ -e $HOME/-error ] && echo "Exit $PKGURL " && break
+  [ -e $HOME/ydfs/tarballs/`basename $PKGURL`.start ] && [ -e $HOME/ydfs/tarballs/`basename $PKGURL` ] && rm $HOME/ydfs/tarballs/`basename $PKGURL`
+  [ ! -e $HOME/ydfs/tarballs/`basename $PKGURL` ] && touch $HOME/ydfs/tarballs/`basename $PKGURL`.start && echo "Get $PKGURL" && wget --trust-server-name --tries=5 -w 6 --no-check-certificate --output-document=$HOME/ydfs/tarballs/`basename $PKGURL` $PKGURL && rm $HOME/ydfs/tarballs/`basename $PKGURL`.start
+  test -s $HOME/ydfs/tarballs/`basename $PKGURL` || rm $HOME/ydfs/tarballs/`basename $PKGURL`
+  [ ! -e $HOME/ydfs/tarballs/`basename $PKGURL` ] && echo "`basename $PKGURL` not found " && touch $HOME/ydfs-error
+  [ -e $HOME/ydfs-error ] && echo "Exit $PKGURL " && break
   # ? DBKVER=$KERNEL3 
-  $HOME_DIBAB/scripts/build_archive $HOME//tarballs/`basename $PKGURL` || touch $HOME/-error
-  [ -e $HOME/-error ] && tail -100 $(cat $HOME//.last-error) && echo -n "full log is " && cat $HOME//.last-error
-  [ -e $HOME/-error ] && echo "Exit $0 $PKGURL " && break
+  $HOME_DIBAB/scripts/build_archive $HOME/ydfs/tarballs/`basename $PKGURL` || touch $HOME/ydfs-error
+  [ -e $HOME/ydfs-error ] && tail -100 $(cat $HOME/ydfs/.last-error) && echo -n "full log is " && cat $HOME/ydfs/.last-error
+  [ -e $HOME/ydfs-error ] && echo "Exit $0 $PKGURL " && break
 done
 
-[ -e $HOME/-error ] && exit 1
+[ -e $HOME/ydfs-error ] && exit 1
 
 if [ ! -e /$HOME/$CARCH/include/ladspa.h ] && [ "$CARCH" != "arm" ]
 then
-    cd $HOME//src
+    cd $HOME/ydfs/src
     cp -fR $HOME_DIBAB/ladspa_sdk .
     cd ladspa_sdk/src
     mkdir ../plugins
