new looped base deps for Arch

diff --git a/3.0/scripts/echo-archpkg b/3.0/scripts/echo-archpkg
--- a/3.0/scripts/echo-archpkg
+++ b/3.0/scripts/echo-archpkg
@@ -1,17 +1,35 @@
 #!/bin/bash
-install -d $HOME/archpkg
-URL=https://projects.archlinux.org/svntogit/packages.git/plain/trunk/PKGBUILD?h=packages
-URL2=https://projects.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages
 PKG=$1
 SHORT=${PKG:0:2}
-URL3=https://aur.archlinux.org/packages/$SHORT/$1/PKGBUILD
-ERROR=0
+install -d $HOME/archpkg
+cd $HOME/archpkg
+URL2=https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/$1/trunk/PKGBUILD
+URL1=https://raw.githubusercontent.com/archlinux/svntogit-community/packages/$1/trunk/PKGBUILD
+URL4=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=
+URL6=https://aur.archlinux.org/packages/$SHORT/$1/PKGBUILD
+URL7=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$PKG
+URL8=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$PKG
+
+OPTION=" --no-check-certificate" 
+OPTION=" -q --no-check-certificate" 
 if [ ! -e $HOME/archpkg/$PKG ]
 then
-wget --no-check-certificate -q "$URL""/""$1" -O $HOME/archpkg/$PKG || wget --no-check-certificate -q "$URL2""/""$1" -O $HOME/archpkg/$PKG || wget --no-check-certificate -q "$URL3" -O $HOME/archpkg/$PKG || ERROR=1
+wget $OPTION "$URL1" -O $HOME/archpkg/$PKG || \
+	wget $OPTION "$URL2" -O $HOME/archpkg/$PKG || \
+	wget $OPTION "$URL3" -O $HOME/archpkg/$PKG || \
+	wget $OPTION "$URL4" -O $HOME/archpkg/$PKG || \
+	wget $OPTION "$URL6" -O $HOME/archpkg/$PKG || \
+	wget $OPTION "$URL7" -O $HOME/archpkg/$PKG || \
+	ERROR=1
 fi
 
-[ "$ERROR" = 1 ] && exit 1
+test -s $HOME/archpkg/$PKG
+if [ $? = 1 ]
+then
+ echo "Error, delete $HOME/archpkg/$PKG which is empty"
+ rm $HOME/archpkg/$PKG
+ exit 1
+fi
 
 source $HOME/archpkg/$PKG
 
