Gcc to build libreoffice

diff --git a/2.9/scripts/includes/libreoffice b/2.9/scripts/includes/libreoffice
--- a/2.9/scripts/includes/libreoffice
+++ b/2.9/scripts/includes/libreoffice
@@ -1,10 +1,6 @@
 #!/bin/bash
   if [ -e librelogo ] 
   then
-	#install -d workdir/UnpackedTarball/libtommath
-	#cp $HOME/$ARCH/lib/libtommath* workdir/UnpackedTarball/libtommath
-	#cp $HOME/$ARCH/include/tommath* workdir/UnpackedTarball/libtommath
-	# for correct file install into package dir
         [ -e "$PREFIX/bin/libreoffice" ] && echo "$PREFIX/bin/libreoffice exists, skip build libreoffice" && exit 0
 	install -d src
 	LIBREOFFICE=`basename $PWD|cut -d'-' -f2`
@@ -18,12 +14,12 @@
 	export ACLOCAL="aclocal" 
 	export ACLOCAL_FLAGS="-I/$PREFIX/share/aclocal -I$HOME/$ARCH/share/aclocal" 
 	install -d $HOME/ydfs/src/libreoffice-$LIBREOFFICE/libreoffice-translations-$LIBREOFFICE
-	export CFLAGS=" $CFLAGS -I$HOME/$ARCH/include/gpgme++/ "
-	export CFLAGS=" $CFLAGS -I$HOME/$ARCH/include/nss/ "
-	export CXXFLAGS=$CFLAGS CC=clang CXX=clang++ 
+	#export CFLAGS=" $CFLAGS -I$HOME/$ARCH/include/gpgme++/ "
+	#export CFLAGS=" $CFLAGS -I$HOME/$ARCH/include/nss/ "
+	#export CXXFLAGS=$CFLAGS CC=clang CXX=clang++ NM=llvm-nm
+	export CXXFLAGS=$CFLAGS CC=gcc CXX=g++ 
 	CONFIGURE_OPTS=""
 	env > env.log
- 	# [ "$ARCH" = "x86" ] && sed -i "s/__builtin_mul_overflow/__DISABLE_X86__builtin_mul_overflow/" include/o3tl/safeint.hxx
         [ "$ARCH" = "x86_64" ] && CONFIGURE_OPTS=" --with-boost-libdir=/usr/lib/x86_64-linux-gnu/ "
         if [ "$ARCH" = "x86" ] 
 	then
@@ -35,8 +31,6 @@
 		  	  echo install -d workdir/HelpTarget/$dir/$lang/$dir.idxl
 			done
 		 done
-		# Bug at solenv/gbuild/HelpTarget.mk:452
-		# sed -i -e '451,452d' solenv/gbuild/HelpTarget.mk
 	fi
 
 	install -d $PREFIX/lib/java
@@ -48,16 +42,13 @@
 	_additional_source_url="https://dev-www.libreoffice.org/src"
 	_additional_source_url2="https://dev-www.libreoffice.org/extern"
 	install -d tar
-for TAR in 35c94d2df8893241173de1d16b6034c0-swingExSrc.zip 798b2ffdc8bcfe7bca2cf92b62caf685-rhino1_5R5.zip a7983f859eafb2677d7ff386a023bc40-xsltml_2.1.2.zip 0168229624cfac409e766913506961a8-ucpp-1.3.2.tar.gz language-subtag-registry-2021-03-05.tar.bz2 17410483b5b5f267aa18b7e00b65e6e0-hsqldb_1_8_0.zip d8bd5eed178db6e2b18eeed243f85aa8-flute-1.1.6.zip ba2930200c9f019c2d93a8c88c651a0f-flow-engine-0.9.4.zip pdfium-4500.tar.bz2 dtoa-20180411.tgz lxml-4.1.1.tgz Firebird-3.0.7.33374-0.tar.bz2 zxing-cpp-1.1.1.tar.gz skia-m90-45c57e116ee0ce214bdf78405a4762722e4507d9.tar.xz libcmis-0.5.2.tar.xz 8249374c274932a21846fa7629c2aa9b-officeotron-0.7.4-master.jar odfvalidator-1.2.0-incubating-SNAPSHOT-jar-with-dependencies-971c54fd38a968f5860014b44301872706f9e540.jar f543e6e2d7275557a839a164941c0a86e5f2c3f2a0042bfc434c88c6dde9e140-opens___.ttf 185d60944ea767075d27247c3162b3bc-unowinreg.dll
-do
-  NAME=`basename $TAR`
-  [ ! -e tar/$NAME ] && wget  --no-check-certificate $_additional_source_url/$TAR -O tar/$NAME
-  [ ! -e tar/$NAME ] && wget  --no-check-certificate $_additional_source_url2/$TAR -O tar/$NAME
-  [ ! -e tar/$NAME ] && echo "$NAME is missing" && exit 1
-done
-
-	export CPPFLAGS="$CPPFLAGS -DU_USING_ICU_NAMESPACE=1 "
-	# [ "$ARCH" = "x86" ] &&	./autogen.sh --with-java=/usr/bin/java --with-vendor="YourDistroFromScratch"  --prefix=$PREFIX --exec-prefix=$PREFIX --sysconfdir=$HOME/$ARCH/etc --with-lang="fr en-GB"
+	for TAR in ${_additional_source_url}/35c94d2df8893241173de1d16b6034c0-swingExSrc.zip ${_additional_source_url}/798b2ffdc8bcfe7bca2cf92b62caf685-rhino1_5R5.zip ${_additional_source_url}/a7983f859eafb2677d7ff386a023bc40-xsltml_2.1.2.zip ${_additional_source_url}/0168229624cfac409e766913506961a8-ucpp-1.3.2.tar.gz ${_additional_source_url}/language-subtag-registry-2021-03-05.tar.bz2 ${_additional_source_url}/17410483b5b5f267aa18b7e00b65e6e0-hsqldb_1_8_0.zip ${_additional_source_url}/d8bd5eed178db6e2b18eeed243f85aa8-flute-1.1.6.zip ${_additional_source_url}/ba2930200c9f019c2d93a8c88c651a0f-flow-engine-0.9.4.zip ${_additional_source_url}/pdfium-4500.tar.bz2 ${_additional_source_url}/dtoa-20180411.tgz ${_additional_source_url}/lxml-4.1.1.tgz ${_additional_source_url}/Firebird-3.0.7.33374-0.tar.bz2 ${_additional_source_url}/zxing-cpp-1.1.1.tar.gz ${_additional_source_url}/skia-m90-45c57e116ee0ce214bdf78405a4762722e4507d9.tar.xz ${_additional_source_url}/libcmis-0.5.2.tar.xz ${_additional_source_url2}/8249374c274932a21846fa7629c2aa9b-officeotron-0.7.4-master.jar ${_additional_source_url2}/odfvalidator-1.2.0-incubating-SNAPSHOT-jar-with-dependencies-971c54fd38a968f5860014b44301872706f9e540.jar ${_additional_source_url2}/f543e6e2d7275557a839a164941c0a86e5f2c3f2a0042bfc434c88c6dde9e140-opens___.ttf ${_additional_source_url2}/185d60944ea767075d27247c3162b3bc-unowinreg.dll
+		do
+		  NAME=`basename $TAR`
+		  echo -n $NAME 
+		  [ ! -e tar/$NAME ] && wget  --no-check-certificate $TAR -O tar/$NAME
+		  [ ! -e tar/$NAME ] && echo "$NAME is missing" && exit 1
+		done
 	./autogen.sh --with-vendor="YourDistroFromScratch"  \
 		--with-external-tar=$PWD/tar \
 		--prefix=$PREFIX --exec-prefix=$PREFIX --sysconfdir=$HOME/$ARCH/etc \
@@ -135,15 +126,19 @@ done
 
 	echo "Run : make build / make build-nocheck / make distro-pack-install "
 	# bash
-	for STEP in 1 2 3  4 5 6 7 8 9 
+	for STEP in 1 # 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
 	do
 		echo "Make $STEP"
-		make build-nocheck || ranlib workdir/LinkTarget/StaticLibrary/*.a 
+		date
+		make build-nocheck || exit 1 # || ranlib workdir/LinkTarget/StaticLibrary/*.a 
 	done
+		date
 	make build-nocheck || make GMAKE_OPTIONS='VERBOSE=1' 
 	echo "Make build-nocheck"
-	make build-nocheck 
+		date
+	make build-nocheck || exit 1
 	echo "Make distro-pack-install"
+		date
 	make distro-pack-install  
 	echo "Check $PREFIX/lib/libreoffice/program/soffice"
         [ ! -e $PREFIX/lib/libreoffice/program/soffice ] && exit 1
